FROM eclipse-temurin:8-jdk-alpine
WORKDIR /opt
RUN apk add --no-cache curl unzip && \
    curl -sL https://github.com/kekingcn/file-online-preview/releases/download/v4.4.0/keking-file-online-preview-4.4.0.zip -o kkfileview.zip && \
    unzip -o kkfileview.zip && \
    rm -f kkfileview.zip && \
    mv keking-file-online-preview-4.4.0 kkFileView-4.4.0 && \
    apk del curl unzip
EXPOSE 8012
CMD ["java", "-Dfile.encoding=UTF-8", "-jar", "/opt/kkFileView-4.4.0/lib/file-online-preview.jar"]
