sonar.projectKey=dong-medicine-platform
sonar.sources=dong-medicine-backend/src/main,dong-medicine-frontend/src
sonar.tests=dong-medicine-backend/src/test,dong-medicine-frontend/src/__tests__
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=dong-medicine-backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=dong-medicine-frontend/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/target/**,**/dist/**
